# Generated by Django 3.2.3 on 2021-06-06 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Locations', '0001_initial'),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasPunchIn', models.BooleanField(default=False)),
                ('punchInTime', models.DateTimeField()),
                ('punchOutTime', models.DateTimeField(blank=True, null=True)),
                ('totalTimeServed', models.TimeField(blank=True, null=True)),
                ('Note', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.account')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Locations.locations')),
            ],
        ),
        migrations.CreateModel(
            name='PostMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Account/Dummy/')),
                ('Note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DumyAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasPunchIn', models.BooleanField(default=False)),
                ('punchInTime', models.DateTimeField(auto_now=True)),
                ('Note', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account.account')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Locations.locations')),
            ],
        ),
        migrations.CreateModel(
            name='Attendances',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Account.account')),
                ('attendances', models.ManyToManyField(blank=True, null=True, to='Attendance.Attendance')),
            ],
        ),
    ]
